// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pulsar.API.Repositories.Data;

#nullable disable

namespace Pulsar.API.Migrations
{
    [DbContext(typeof(PulsarDbContext))]
    [Migration("20260521130552_AdicionarSugestoesCompletas")]
    partial class AdicionarSugestoesCompletas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("ScoreId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.AlertaSugestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlertaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SugestaoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SugestaoId");

                    b.HasIndex("AlertaId", "SugestaoId")
                        .IsUnique();

                    b.ToTable("AlertaSugestoes");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.LeituraClimatica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ChuvaMmH")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<double>("IndiceUv")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SubprefeituraId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("VentoKmH")
                        .HasColumnType("REAL");

                    b.Property<double>("VisibilidadeKm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SubprefeituraId", "Timestamp");

                    b.ToTable("LeiturasClimaticas");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Regioes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Centro"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Norte"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Sul"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Leste"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Oeste"
                        });
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.ScorePerigo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faixa")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LeituraId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubprefeituraId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LeituraId");

                    b.HasIndex("SubprefeituraId", "Timestamp");

                    b.ToTable("ScoresPerigo");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Subprefeitura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Subprefeituras");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.5505,
                            Longitude = -46.633299999999998,
                            Nome = "Sé",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.556100000000001,
                            Longitude = -46.601900000000001,
                            Nome = "Mooca",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.526,
                            Longitude = -46.708399999999997,
                            Nome = "Lapa",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.566299999999998,
                            Longitude = -46.692900000000002,
                            Nome = "Pinheiros",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.587399999999999,
                            Longitude = -46.6355,
                            Nome = "Vila Mariana",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.567399999999999,
                            Longitude = -46.737099999999998,
                            Nome = "Butantã",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.500299999999999,
                            Longitude = -46.625799999999998,
                            Nome = "Santana/Tucuruvi",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.4986,
                            Longitude = -46.657800000000002,
                            Nome = "Casa Verde/Cachoeirinha",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.467300000000002,
                            Longitude = -46.688000000000002,
                            Nome = "Freguesia do Ó/Brasilândia",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.4726,
                            Longitude = -46.754100000000001,
                            Nome = "Pirituba/Jaraguá",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.403099999999998,
                            Longitude = -46.762099999999997,
                            Nome = "Perus",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.461200000000002,
                            Longitude = -46.5959,
                            Nome = "Tremembé/Jacanã",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.651,
                            Longitude = -46.707299999999996,
                            Nome = "Santo Amaro",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.6267,
                            Longitude = -46.767400000000002,
                            Nome = "Campo Limpo",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.706900000000001,
                            Longitude = -46.6875,
                            Nome = "Capela do Socorro",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.659700000000001,
                            Longitude = -46.6449,
                            Nome = "Cidade Ademar",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.709299999999999,
                            Longitude = -46.745100000000001,
                            Nome = "M'Boi Mirim",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.8246,
                            Longitude = -46.729599999999998,
                            Nome = "Parelheiros",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.5381,
                            Longitude = -46.535400000000003,
                            Nome = "Aricanduva/Formosa/Carrão",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.6082,
                            Longitude = -46.426000000000002,
                            Nome = "Cidade Tiradentes",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.506,
                            Longitude = -46.468800000000002,
                            Nome = "Ermelino Matarazzo",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.564,
                            Longitude = -46.411299999999997,
                            Nome = "Guaianases",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.514700000000001,
                            Longitude = -46.405700000000003,
                            Nome = "Itaim Paulista",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.537600000000001,
                            Longitude = -46.457000000000001,
                            Nome = "Itaquera",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.522400000000001,
                            Longitude = -46.530999999999999,
                            Nome = "Penha",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000026"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.618200000000002,
                            Longitude = -46.487299999999998,
                            Nome = "São Mateus",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000027"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.511500000000002,
                            Longitude = -46.445099999999996,
                            Nome = "São Miguel Paulista",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000028"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.591799999999999,
                            Longitude = -46.488100000000003,
                            Nome = "Sapopemba",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000029"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.586300000000001,
                            Longitude = -46.567,
                            Nome = "Vila Prudente",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000030"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.5868,
                            Longitude = -46.6083,
                            Nome = "Ipiranga",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.6554,
                            Longitude = -46.6432,
                            Nome = "Jabaquara",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.5138,
                            Longitude = -46.593800000000002,
                            Nome = "Vila Maria/Vila Guilherme",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Sugestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FaixaRisco")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Categoria", "FaixaRisco");

                    b.ToTable("Sugestoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Precipitação leve esperada. Carregue um guarda-chuva ao sair de casa para evitar surpresas.",
                            FaixaRisco = 0,
                            Titulo = "Chuva leve prevista"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Mantenha um guarda-chuva próximo. Chuviscos podem ocorrer sem aviso prévio, especialmente no final da tarde.",
                            FaixaRisco = 0,
                            Titulo = "Guarde o guarda-chuva acessível"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Mesmo com chuva fraca, verifique o estado de bueiros na sua rua e evite caminhar próximo a calçadas alagadas.",
                            FaixaRisco = 0,
                            Titulo = "Atenção a bueiros e valetas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chuva moderada na região. Evite áreas historicamente alagáveis, reduza a velocidade ao dirigir e mantenha distância segura.",
                            FaixaRisco = 1,
                            Titulo = "Chuva moderada"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Verifique o histórico de alagamentos da sua rota antes de sair. Marginais, viadutos e pontos baixos são os primeiros a alagar.",
                            FaixaRisco = 1,
                            Titulo = "Evite áreas alagáveis"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Pista molhada aumenta a distância de frenagem em até 2x. Reduza a velocidade e mantenha distância segura do veículo à frente.",
                            FaixaRisco = 1,
                            Titulo = "Reduza a velocidade no trânsito"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chuva intensa com risco elevado de alagamentos e deslizamentos. Evite viadutos e marginais. Procure abrigo seguro e afaste-se de encostas.",
                            FaixaRisco = 2,
                            Titulo = "Chuva intensa — risco de alagamento"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000020"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Em áreas de encosta, saia imediatamente e dirija-se ao abrigo mais próximo. Ligue para a Defesa Civil: 199.",
                            FaixaRisco = 2,
                            Titulo = "Risco de deslizamento"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000021"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CHUVA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "30 cm de água em movimento podem derrubar um adulto e 60 cm podem arrastar um veículo. Nunca tente atravessar vias alagadas.",
                            FaixaRisco = 2,
                            Titulo = "Nunca atravesse enxurradas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Ventos fracos. Condições normais de circulação. Nenhuma medida especial necessária.",
                            FaixaRisco = 0,
                            Titulo = "Vento fraco"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000022"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Vento suave. Atividades ao ar livre podem ser realizadas normalmente. Boa condição para caminhadas e esportes externos.",
                            FaixaRisco = 0,
                            Titulo = "Condições favoráveis ao ar livre"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000023"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Mesmo com vento fraco, objetos leves podem ser deslocados. Feche janelas e portas ao deixar o ambiente.",
                            FaixaRisco = 0,
                            Titulo = "Verifique janelas abertas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Rajadas moderadas de vento. Atenção a objetos soltos em janelas e sacadas. Motoristas de veículos altos devem redobrar cuidado.",
                            FaixaRisco = 1,
                            Titulo = "Rajadas de vento"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000024"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Recolha vasos, cadeiras e outros objetos de sacadas e áreas externas. Rajadas podem deslocar itens e causar acidentes.",
                            FaixaRisco = 1,
                            Titulo = "Proteja objetos em sacadas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000025"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Rajadas de vento podem abrir portas com força inesperada. Segure a maçaneta ao abrir portas externas.",
                            FaixaRisco = 1,
                            Titulo = "Cuidado ao abrir portas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Ventos fortes com risco de queda de árvores, placas e estruturas. Evite áreas arborizadas e lugares abertos. Não fique próximo a construções.",
                            FaixaRisco = 2,
                            Titulo = "Ventos fortes — risco de queda"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000026"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Ventos fortes podem derrubar galhos e árvores inteiras. Mantenha-se longe de árvores, postes e coberturas improvisadas.",
                            FaixaRisco = 2,
                            Titulo = "Evite ficar sob árvores"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000027"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Caminhões, ônibus e veículos altos têm risco de tombamento. Motoristas devem reduzir velocidade e evitar pistas elevadas.",
                            FaixaRisco = 2,
                            Titulo = "Risco para veículos altos"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Visibilidade dentro dos padrões normais. Condições de trânsito sem restrições por neblina.",
                            FaixaRisco = 0,
                            Titulo = "Visibilidade boa"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000028"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Visibilidade adequada para todas as atividades. Continue com as atividades normais com a atenção de sempre.",
                            FaixaRisco = 0,
                            Titulo = "Sem restrições de visibilidade"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000029"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Em dias frios e úmidos, neblina leve pode surgir nas primeiras horas da manhã. Fique atento ao sair cedo.",
                            FaixaRisco = 0,
                            Titulo = "Neblina matinal pode ocorrer"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Neblina reduzindo visibilidade. Ative o farol baixo mesmo de dia, reduza a velocidade e aumente a distância do veículo à frente.",
                            FaixaRisco = 1,
                            Titulo = "Neblina leve"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000030"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Com neblina, o farol baixo melhora tanto sua visibilidade quanto a percepção dos outros motoristas. Nunca use farol alto — aumenta o ofuscamento.",
                            FaixaRisco = 1,
                            Titulo = "Use farol baixo obrigatório"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000031"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Com visibilidade reduzida, aumente para pelo menos 4 segundos a distância do veículo à frente. Evite ultrapassagens.",
                            FaixaRisco = 1,
                            Titulo = "Aumente a distância segura"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Neblina densa com visibilidade abaixo de 200m. Evite dirigir se possível. Se necessário, use faróis e pisca-alerta.",
                            FaixaRisco = 2,
                            Titulo = "Neblina densa — visibilidade crítica"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000032"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Se a visibilidade for inferior a 50m, pare o veículo em local seguro fora da pista e acione o pisca-alerta. Aguarde a neblina dissipar.",
                            FaixaRisco = 2,
                            Titulo = "Pare em local seguro se necessário"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000033"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "NEBLINA",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Com neblina densa, pedestres devem usar roupas claras ou refletivas e evitar caminhar em vias com tráfego de veículos.",
                            FaixaRisco = 2,
                            Titulo = "Pedestres: use roupas claras"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Índice UV baixo. Proteção solar básica é recomendada, especialmente para pessoas de pele clara.",
                            FaixaRisco = 0,
                            Titulo = "Índice UV baixo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000034"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Com índice UV baixo, um protetor solar FPS 15 já oferece proteção adequada para a maioria das pessoas em atividades ao ar livre.",
                            FaixaRisco = 0,
                            Titulo = "Protetor solar FPS 15 suficiente"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000035"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Índice UV favorável para atividades ao ar livre. Aproveite mas lembre-se de se hidratar bem.",
                            FaixaRisco = 0,
                            Titulo = "Bom momento para atividades externas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Use protetor solar FPS 30 ou superior. Evite exposição prolongada entre 10h e 16h. Utilize óculos de sol e chapéu.",
                            FaixaRisco = 1,
                            Titulo = "Índice UV moderado"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000036"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chapéu de aba larga e óculos com proteção UV são essenciais. Reaplicar protetor solar a cada 2 horas ou após suar.",
                            FaixaRisco = 1,
                            Titulo = "Use chapéu e óculos de sol"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000037"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Crianças e idosos são mais sensíveis à radiação UV. Aplique protetor solar antes de sair e evite exposição direta nos horários de pico.",
                            FaixaRisco = 1,
                            Titulo = "Proteja crianças e idosos"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Índice UV muito alto. Evite exposição ao sol entre 10h e 16h. Use protetor FPS 50+, roupas protetoras e procure a sombra.",
                            FaixaRisco = 2,
                            Titulo = "Índice UV elevado — proteção obrigatória"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000038"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Com UV elevado, a pele pode queimar em menos de 15 minutos de exposição sem proteção. Mantenha-se na sombra ou em ambientes internos.",
                            FaixaRisco = 2,
                            Titulo = "Risco de queimaduras em minutos"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000039"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "UV",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Além da proteção solar, beba pelo menos 2 litros de água por dia. Calor intenso combinado com UV alto aumenta risco de desidratação e insolação.",
                            FaixaRisco = 2,
                            Titulo = "Hidratação reforçada"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Condições climáticas dentro da normalidade. Aproveite o dia com cautela e mantenha-se informado sobre atualizações.",
                            FaixaRisco = 0,
                            Titulo = "Condições climáticas favoráveis"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000040"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Mesmo com baixo risco, acompanhe as atualizações do Pulsar a cada 15 minutos. Condições climáticas podem mudar rapidamente.",
                            FaixaRisco = 0,
                            Titulo = "Mantenha-se informado"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000041"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Dia com baixo risco climático. Ótimo para atividades ao ar livre. Leve água e protetor solar como precaução básica.",
                            FaixaRisco = 0,
                            Titulo = "Bom dia para atividades externas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Condições climáticas requerem atenção. Mantenha-se informado e siga as orientações dos órgãos competentes. Evite exposição desnecessária.",
                            FaixaRisco = 1,
                            Titulo = "Atenção às condições climáticas"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000042"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Antes de sair, verifique o score da sua região no Pulsar. Com risco moderado, prefira horários com menor intensidade climática.",
                            FaixaRisco = 1,
                            Titulo = "Planeje suas saídas com antecedência"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000043"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Mantenha no carro: lanternas, cobertor, kit de primeiros socorros, carregador portátil e água. Em situações moderadas, a preparação faz a diferença.",
                            FaixaRisco = 1,
                            Titulo = "Kit de emergência no carro"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Alerta climático ativo na região. Siga as orientações da Defesa Civil, evite áreas de risco e mantenha crianças e idosos em local seguro.",
                            FaixaRisco = 2,
                            Titulo = "Alerta climático ativo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000044"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Em situação de risco, ligue 199 (Defesa Civil) ou 193 (Bombeiros). Não espere a situação piorar para pedir ajuda.",
                            FaixaRisco = 2,
                            Titulo = "Ligue para a Defesa Civil"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000045"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "GERAL",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Com alerta ativo, fique em local seguro. Se precisar sair, informe alguém sobre seu destino e rota. Prefira rotas conhecidas e seguras.",
                            FaixaRisco = 2,
                            Titulo = "Evite deslocamentos desnecessários"
                        });
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.UsuarioRegiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("UsuarioId", "RegiaoId")
                        .IsUnique();

                    b.ToTable("UsuarioRegioes");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Regiao", "Regiao")
                        .WithMany("Alertas")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pulsar.API.Domain.Entities.ScorePerigo", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.AlertaSugestao", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Alerta", "Alerta")
                        .WithMany("AlertaSugestoes")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulsar.API.Domain.Entities.Sugestao", "Sugestao")
                        .WithMany("AlertaSugestoes")
                        .HasForeignKey("SugestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Sugestao");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.LeituraClimatica", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Subprefeitura", "Subprefeitura")
                        .WithMany("Leituras")
                        .HasForeignKey("SubprefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subprefeitura");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.ScorePerigo", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.LeituraClimatica", "Leitura")
                        .WithMany()
                        .HasForeignKey("LeituraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pulsar.API.Domain.Entities.Subprefeitura", "Subprefeitura")
                        .WithMany("Scores")
                        .HasForeignKey("SubprefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leitura");

                    b.Navigation("Subprefeitura");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Subprefeitura", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Regiao", "Regiao")
                        .WithMany("Subprefeituras")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.UsuarioRegiao", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Regiao", "Regiao")
                        .WithMany("Favoritos")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulsar.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Alerta", b =>
                {
                    b.Navigation("AlertaSugestoes");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Favoritos");

                    b.Navigation("Subprefeituras");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Subprefeitura", b =>
                {
                    b.Navigation("Leituras");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Sugestao", b =>
                {
                    b.Navigation("AlertaSugestoes");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Favoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
