// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulsar.API.Repositories.Data;

#nullable disable

namespace Pulsar.API.Migrations
{
    [DbContext(typeof(PulsarDbContext))]
    partial class PulsarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulsar.API.Domain.Entities.AgregadoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ChuvaTotalMm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("LeiturasAlto")
                        .HasColumnType("integer");

                    b.Property<int>("LeiturasBaixo")
                        .HasColumnType("integer");

                    b.Property<int>("LeiturasCount")
                        .HasColumnType("integer");

                    b.Property<int>("LeiturasModerado")
                        .HasColumnType("integer");

                    b.Property<double>("ScoreAlagamentoMax")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreMax")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreMedio")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreMin")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SubprefeituraId")
                        .HasColumnType("uuid");

                    b.Property<double>("TemperaturaMaxC")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperaturaMinC")
                        .HasColumnType("double precision");

                    b.Property<double>("UvMax")
                        .HasColumnType("double precision");

                    b.Property<double>("VentoMaxKmH")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SubprefeituraId", "Dia")
                        .IsUnique();

                    b.ToTable("AgregadosDiarios");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.AssinaturaPush", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlertaAlto")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlertaModerado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ResumoDiario")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("AssinaturasPush");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.LeituraClimatica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ChuvaMmH")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("IndiceUv")
                        .HasColumnType("double precision");

                    b.Property<double>("SensacaoTermica")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SubprefeituraId")
                        .HasColumnType("uuid");

                    b.Property<double>("TemperaturaC")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Umidade")
                        .HasColumnType("double precision");

                    b.Property<double>("VentoKmH")
                        .HasColumnType("double precision");

                    b.Property<double>("VisibilidadeKm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SubprefeituraId", "Timestamp");

                    b.ToTable("LeiturasClimaticas");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.NotificacaoEnviada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gatilho")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SubprefeituraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubprefeituraId");

                    b.HasIndex("UsuarioId", "Chave")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "EnviadoEm");

                    b.ToTable("NotificacoesEnviadas");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.OcorrenciaAlagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CdIdentificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FonteOriginal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NmSubprefeitura")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataOcorrencia");

                    b.HasIndex("CdIdentificador", "Tipo")
                        .IsUnique();

                    b.ToTable("OcorrenciasAlagamento");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.PrevisaoClimatica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ChuvaMm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ColetadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CondicaoCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("CondicaoDescricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("InstantePrevisto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ProbabilidadeChuva")
                        .HasColumnType("double precision");

                    b.Property<double?>("RajadaKmH")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SubprefeituraId")
                        .HasColumnType("uuid");

                    b.Property<double>("TemperaturaC")
                        .HasColumnType("double precision");

                    b.Property<double>("VentoKmH")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SubprefeituraId", "InstantePrevisto")
                        .IsUnique();

                    b.ToTable("PrevisoesClimaticas");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Regioes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FusoHorario = "America/Sao_Paulo",
                            Nome = "Centro"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FusoHorario = "America/Sao_Paulo",
                            Nome = "Leste"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FusoHorario = "America/Sao_Paulo",
                            Nome = "Norte"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FusoHorario = "America/Sao_Paulo",
                            Nome = "Oeste"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FusoHorario = "America/Sao_Paulo",
                            Nome = "Sul"
                        });
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.ScorePerigo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Chuva3hMm")
                        .HasColumnType("double precision");

                    b.Property<double>("Chuva48hMm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Faixa")
                        .HasColumnType("integer");

                    b.Property<int>("FaixaAlagamento")
                        .HasColumnType("integer");

                    b.Property<int>("FaixaCalor")
                        .HasColumnType("integer");

                    b.Property<int>("FaixaVento")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeituraId")
                        .HasColumnType("uuid");

                    b.Property<int>("PerigoPrincipal")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubprefeituraId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.Property<double>("ValorAlagamento")
                        .HasColumnType("double precision");

                    b.Property<double>("ValorCalor")
                        .HasColumnType("double precision");

                    b.Property<double>("ValorVento")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LeituraId");

                    b.HasIndex("SubprefeituraId", "Timestamp");

                    b.ToTable("ScoresPerigo");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Subprefeitura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Subprefeituras");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.548359999999999,
                            Longitude = -46.639876000000001,
                            Nome = "Sé",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.563777999999999,
                            Longitude = -46.533800999999997,
                            Nome = "Aricanduva-Formosa-Carrão",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.584802,
                            Longitude = -46.400846999999999,
                            Nome = "Cidade Tiradentes",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.501366999999998,
                            Longitude = -46.488332,
                            Nome = "Ermelino Matarazzo",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.545071,
                            Longitude = -46.407617000000002,
                            Nome = "Guaianases",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.50628,
                            Longitude = -46.399180999999999,
                            Nome = "Itaim Paulista",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.559878999999999,
                            Longitude = -46.458407000000001,
                            Nome = "Itaquera",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.548745,
                            Longitude = -46.588138000000001,
                            Nome = "Mooca",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.521186,
                            Longitude = -46.516173999999999,
                            Nome = "Penha",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.60557,
                            Longitude = -46.509548000000002,
                            Nome = "Sapopemba",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.61355,
                            Longitude = -46.450006000000002,
                            Nome = "São Mateus",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.495421,
                            Longitude = -46.437505000000002,
                            Nome = "São Miguel",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.593596999999999,
                            Longitude = -46.558053999999998,
                            Nome = "Vila Prudente",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.476931,
                            Longitude = -46.664169000000001,
                            Nome = "Casa Verde-Limão-Cachoeirinha",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.461469000000001,
                            Longitude = -46.691465999999998,
                            Nome = "Freguesia-Brasilândia",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.422594,
                            Longitude = -46.587577000000003,
                            Nome = "Jaçanã-Tremembé",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.421113999999999,
                            Longitude = -46.773601999999997,
                            Nome = "Perus-Anhanguera",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.465171999999999,
                            Longitude = -46.736835999999997,
                            Nome = "Pirituba-Jaraguá",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.478587000000001,
                            Longitude = -46.627833000000003,
                            Nome = "Santana-Tucuruvi",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.504908,
                            Longitude = -46.585228000000001,
                            Nome = "Vila Maria-Vila Guilherme",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.585713999999999,
                            Longitude = -46.743287000000002,
                            Nome = "Butantã",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.528213999999998,
                            Longitude = -46.713954000000001,
                            Nome = "Lapa",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.573253000000001,
                            Longitude = -46.688825999999999,
                            Nome = "Pinheiros",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.645517000000002,
                            Longitude = -46.759993999999999,
                            Nome = "Campo Limpo",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.766676,
                            Longitude = -46.679802000000002,
                            Nome = "Capela do Socorro",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000026"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.693687000000001,
                            Longitude = -46.652667000000001,
                            Nome = "Cidade Ademar",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000027"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.619492000000001,
                            Longitude = -46.606712999999999,
                            Nome = "Ipiranga",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000028"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.650549999999999,
                            Longitude = -46.645907999999999,
                            Nome = "Jabaquara",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000029"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.701308000000001,
                            Longitude = -46.756118999999998,
                            Nome = "M'Boi Mirim",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000030"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.890827000000002,
                            Longitude = -46.711489999999998,
                            Nome = "Parelheiros",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.650098,
                            Longitude = -46.688771000000003,
                            Nome = "Santo Amaro",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -23.599433999999999,
                            Longitude = -46.646222000000002,
                            Nome = "Vila Mariana",
                            RegiaoId = new Guid("10000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Sugestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FaixaRisco")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria", "FaixaRisco");

                    b.ToTable("Sugestoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000101"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "ALAGAMENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Se ela apertar, adie saídas e evite áreas baixas e margens de córregos.",
                            FaixaRisco = 1,
                            Ordem = 1,
                            Titulo = "Fique de olho na chuva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000102"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "ALAGAMENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Limpe calhas e ralos e tire do chão documentos e objetos que não podem molhar.",
                            FaixaRisco = 1,
                            Ordem = 2,
                            Titulo = "Prepare a casa"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000103"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "ALAGAMENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Prefira trajetos que você sabe que não alagam e saia com o celular carregado.",
                            FaixaRisco = 1,
                            Ordem = 3,
                            Titulo = "Planeje o caminho"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000104"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "ALAGAMENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Nunca entre em rua alagada a pé ou de carro. Pouca água já pode arrastar um carro e esconder um bueiro aberto.",
                            FaixaRisco = 2,
                            Ordem = 1,
                            Titulo = "Não atravesse água"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000105"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "ALAGAMENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Se a água subir, vá para um ponto elevado e deixe o carro longe de córregos e baixadas.",
                            FaixaRisco = 2,
                            Ordem = 2,
                            Titulo = "Procure um lugar alto"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000106"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "ALAGAMENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Se a água entrar em casa, desligue a chave geral e tire os aparelhos da tomada. Em perigo, ligue 199 ou 193.",
                            FaixaRisco = 2,
                            Ordem = 3,
                            Titulo = "Desligue a energia"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000107"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Guarde vasos, roupas do varal e objetos soltos em sacadas e quintais.",
                            FaixaRisco = 1,
                            Ordem = 1,
                            Titulo = "Recolha o que pode voar"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000108"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Feche portas e janelas e confira se telhas e antenas estão firmes.",
                            FaixaRisco = 1,
                            Ordem = 2,
                            Titulo = "Feche bem a casa"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000109"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Na rua, não estacione nem espere o ônibus embaixo de árvores, placas ou fiação.",
                            FaixaRisco = 1,
                            Ordem = 3,
                            Titulo = "Evite parar sob árvores"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000110"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Se puder, fique dentro de um prédio firme e longe das janelas.",
                            FaixaRisco = 2,
                            Ordem = 1,
                            Titulo = "Fique abrigado"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000111"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Não se abrigue sob árvores, marquises, placas ou postes. Viu fio caído? Não toque e ligue 199.",
                            FaixaRisco = 2,
                            Ordem = 2,
                            Titulo = "Longe de árvores e fios"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000112"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "VENTO",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Tire aparelhos da tomada e evite usar o celular enquanto ele carrega.",
                            FaixaRisco = 2,
                            Ordem = 3,
                            Titulo = "Cuidado com raios"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000113"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CALOR",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Não espere ter sede e leve uma garrafa quando sair.",
                            FaixaRisco = 1,
                            Ordem = 1,
                            Titulo = "Beba água o dia todo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000114"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CALOR",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Evite o sol direto entre 10h e 16h e use roupa leve, chapéu e protetor solar.",
                            FaixaRisco = 1,
                            Ordem = 2,
                            Titulo = "Fuja do sol forte"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000115"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CALOR",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Idosos, crianças, gestantes e pessoas com doenças crônicas sofrem primeiro com o calor. Ofereça água a eles.",
                            FaixaRisco = 1,
                            Ordem = 3,
                            Titulo = "Cuide de quem sente mais"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000116"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CALOR",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Deixe exercício e trabalho pesado ao ar livre para o começo da manhã ou o fim da tarde.",
                            FaixaRisco = 2,
                            Ordem = 1,
                            Titulo = "Diminua o esforço"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000117"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CALOR",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Fique em lugar ventilado ou na sombra e tome banhos frescos.",
                            FaixaRisco = 2,
                            Ordem = 2,
                            Titulo = "Mantenha o corpo fresco"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000118"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "CALOR",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Tontura, fraqueza, náusea, dor de cabeça e cãibras pedem cuidado. Se aparecerem, procure a unidade de saúde mais próxima.",
                            FaixaRisco = 2,
                            Ordem = 3,
                            Titulo = "Conheça os sinais"
                        });
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.TokenRecuperacaoSenha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRecuperacaoSenha");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.UsuarioSubprefeitura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubprefeituraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubprefeituraId");

                    b.HasIndex("UsuarioId", "SubprefeituraId")
                        .IsUnique();

                    b.ToTable("UsuarioSubprefeituras");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.AgregadoDiario", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Subprefeitura", "Subprefeitura")
                        .WithMany()
                        .HasForeignKey("SubprefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subprefeitura");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.AssinaturaPush", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.LeituraClimatica", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Subprefeitura", "Subprefeitura")
                        .WithMany("Leituras")
                        .HasForeignKey("SubprefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subprefeitura");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.NotificacaoEnviada", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Subprefeitura", "Subprefeitura")
                        .WithMany()
                        .HasForeignKey("SubprefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulsar.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subprefeitura");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.PrevisaoClimatica", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Subprefeitura", "Subprefeitura")
                        .WithMany()
                        .HasForeignKey("SubprefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subprefeitura");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.ScorePerigo", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.LeituraClimatica", "Leitura")
                        .WithMany()
                        .HasForeignKey("LeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulsar.API.Domain.Entities.Subprefeitura", "Subprefeitura")
                        .WithMany("Scores")
                        .HasForeignKey("SubprefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leitura");

                    b.Navigation("Subprefeitura");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Subprefeitura", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Regiao", "Regiao")
                        .WithMany("Subprefeituras")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.TokenRecuperacaoSenha", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.UsuarioSubprefeitura", b =>
                {
                    b.HasOne("Pulsar.API.Domain.Entities.Subprefeitura", "Subprefeitura")
                        .WithMany()
                        .HasForeignKey("SubprefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulsar.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subprefeitura");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("Subprefeituras");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Subprefeitura", b =>
                {
                    b.Navigation("Leituras");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Pulsar.API.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Favoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
